theme: jekyll-theme-minimal
title: Mickey Leung's Personal Webpage
description: Ph.D. candidate at Caltech researching turbulence, computational fluid dynamics, and machine learning for flow control and sensing.
